### ISSUE TITLE
ssh_key_path parameter validation

### ISSUE THREAD

**Issue by pellepelster** [1and1/terraform-provider-oneandone#2]
When using the ssh_key_path parameter the terraform apply fails if the ssh key has a password (I guess because it can't derive the public key from it).
Why the need to use the private key? 
I would have expected the possibility to directly specify the public key.

**Comment by jasminSPC** [comment]
According to argument reference ssh key is not a required field. https://github.com/1and1/terraform-provider-oneandone#server 
If neither ssh key or password are provided terraform will use 'FirstPassword', which is returned the first time the server is retrieved after provisioning. 

Either password or ssh key or both are used in terraform `provisioner` which you can see in the [example](https://github.com/1and1/terraform-provider-oneandone/blob/master/example/main.tf#L63-L68
)

As for the option to specify the public key directly we thought it would be impractical to paste the entire key.
