### ISSUE TITLE
runtime error: index out of range when applying oneandone_server

### ISSUE THREAD

**Issue by pellepelster** [1and1/terraform-provider-oneandone#3]
From time to time, when applying a stack via Terraform I get an 'index out of range' runtime error originating in https://github.com/1and1/terraform-provider-oneandone/blob/master/provider/resource_oneandone_server.go#L257
I created a Gist with the two terraform files involved as well as the stacktrace.
The error does not occur every time, to me it seems like waiting some time before applying the second stack that is referencing the first one helps to mitigate the error. In any case I think the plugin should fail more gracefully.

**Comment by jasminSPC** [comment]
I can't find terraform files you mentioned.
